#!/bin/bash
# Usage:
#   check <action>
#
# Arguments:
#   action    $ACTIONS_LIST
ACTIONS_LIST=("lintformat" "lf" "test")

set -euo pipefail

do_lintformat() {
  set -x
  cargo clippy --all-targets --all-features
  cargo fmt --all -- --check
}

do_test() {
  set -x
  cargo test
}

ACTION="${1:-''}"
case "$ACTION" in
lintformat) do_lintformat ;;
lf)         do_lintformat ;;
test)       do_test ;;
*)
  ACTIONS_OPTIONS=${ACTIONS_LIST[*]}
  echo "Actions must be one of: ${ACTIONS_OPTIONS//[[:space:]]/, }"
  exit 1
esac
