#!/bin/bash
# Plots the distribution of zeroes in a filter.
#
# Usage:
#     plot_zeroes <BinaryFuse8|BinaryFuse16|Xor8|Xor16|Fuse8|Fuse16>
#
# Dependencies:
#     pip install matplotlib

case "$1" in
  BinaryFuse8 | BinaryFuse16 | Xor8 | Xor16 | Fuse8 | Fuse16)
    FILTER="$1"
    ;;
  *)
    echo "Invalid filter $1"
    exit 1
    ;;
esac

cargo run -q zeroes --  "$FILTER" > zeroes.txt
python plot_zeroes.py
